---
title: Talk template
output:
  xaringan::moon_reader:
  #  self_contained: TRUE
    includes:
      in_header: conf/style-header.html
    lib_dir: assets
    seal: false
    css: ["default", "conf/css/style.css", "conf/css/fonts.css"]
    nature:
      beforeInit: ["conf/js/gifffer.min.js", "conf/js/style-macros.js"]
---

```{r setup, echo = F}
knitr::opts_chunk$set(
  comment = "#",
  #cache = TRUE,
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.width = 7,
  fig.height = 5.25,
  fig.align = 'center',
  fig.retina = 3
)

# base plot layout
mypar = list(mar = c(3,3,0.5,0.5), mgp = c(1.5, 0.3, 0), tck = -.008)

# xaringan Extra
xaringanExtra::use_xaringan_extra(c("tile_view", "animate_css", "tachyons"))
xaringanExtra::use_extra_styles(
  hover_code_line = TRUE,         #<<
  mute_unhighlighted_code = TRUE  #<<
)
xaringanExtra::use_editable(expires = 1)
xaringanExtra::use_panelset()
```
class: middle, title-slide

<!-- top logo (comment to remove or edit on `conf/css/style.css:23`) -->
<div class="lab-logo"></div>
<!-- <div class="uni-logo"></div> -->

# Title of my talk template

<hr width="65%" align="left" size="0.3" color="orange"></hr>

## My talk subtitle

### Vincent Bellavance, .small[Étudiant à la maîtrise]

<br><br><br><br><br>
[<i class="fa fa-github fa-lg" style="color:#e7e8e2"></i> VincentBellavance/seminar2](https://github.com/VincentBellavance/seminar2)

[<i class="fa fa-twitter fa-lg" style="color:#e7e8e2"></i> @v_bellavance](https://twitter.com/v_bellavance)


---
# Changements de biodiversité

## Plateforme intergouvernementale scientifique et politique sur la biodiversité et les services écosystémiques

---
# Changements de biodiversité

## Perte de biodiversité à l'échelle globale

---
# Changements de biodiversité

## Complexité de la biodiversité

---
# Changements de biodiversité

## Indicateurs de biodiversité

---
# Changements de biodiversité

## Living Planet Index

---
# Changements de biodiversité

## Indicateur à l'échelle nationale

---
# Changements de biodiversité

## Engagement du Québec

---
# Données disponibles au Québec

---
# Aires de distribution d'espèces

---
# Objectifs

---
# Indice Distribution Biodiversité

## Pipeline

---
# Indice Distribution Biodiversité

## Méthode: Données

---
# Indice Distribution Biodiversité

## Méthode: Aires de distribution

---
# Indice Distribution Biodiversité

## Méthode: Calcul de l'indice

---
# Indice Distribution Biodiversité

## Interprétation des résultats

---
# Indice Distribution Biodiversité

## Limites

---
# Conclusion et contributions
